### ISSUE TITLE
[Bug] Clicking notifications in the Windows 10 notification history doesn't open WebMessage

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#134]

**Comment by CSab6482** [comment]
Here's a situation that reminds me a bit of issue #111. I clicked on the incoming notification for the message beginning with "Bruh" and then went into the chat, however, I still received a notification for the next message, even though I was in the chat. Is it possible to collapse notifications/make them disappear when their respective chat is opened?
![Screenshot 2021-03-17 184406](https://user-images.githubusercontent.com/53708281/111549207-2dc6bf80-8752-11eb-8621-b8671a358650.png)

**Comment by sgtaziz** [comment]
done 😎

**Comment by CSab6482** [comment]
I still get this bug, and switching from one chat to another and back to the original doesn't fix it. However, a refresh does make all the delivered tag show up. Also, if two messages are sent, then the delivered tag shows up, but if only one or more than two are sent, I have to refresh to see the delivered tag.
![no read](https://user-images.githubusercontent.com/53708281/113886704-e3ec5a80-978e-11eb-9549-31dd159b5262.png)
![yes read](https://user-images.githubusercontent.com/53708281/113886715-e51d8780-978e-11eb-8fdc-cd85001f2321.png)
