### ISSUE TITLE
no contact pictures

### ISSUE THREAD

**Issue by Joe00** [sgtaziz/WebMessage#62]
I'm using the latest version, but it also didn't work with the previous version
![Bildschirmfoto 2021-02-21 um 10 04 04](https://user-images.githubusercontent.com/12069868/108620425-65c93400-742c-11eb-9bb0-c7d65c845136.png)

**Comment by sgtaziz** [comment]
This is the second time this issue comes up. The contact pictures are served from your phone. So if the pictures are saved in your phone, they should show up. What iOS version are you running? And how do you save your contacts/contact photos?

**Comment by Joe00** [comment]
I use ios 14.4 on an ipad 6th gen. the contact pictures are saved directly into the contact. On the imessage app it shows them correctly

**Comment by sgtaziz** [comment]
I think this might have to do with Apple contacts (the "Do you want to update your contact info for xxx" message you get)
I'll do some more testing and get back to you 👍

**Comment by sgtaziz** [comment]
Should be fixed with the latest update 👍

**Comment by Joe00** [comment]
I just installed the last version on ipad and windows, but I still don't have any contact pictures..

**Comment by sgtaziz** [comment]
Can you provide more information? How do you save your contact photos? Which account are your contacts stored in? Have you tried manually setting a contact photo for a contact?

**Comment by Joe00** [comment]
Which account? How do you mean that? I think it is my icloud account. I always save the pictures manually direct into the contact

**Comment by sgtaziz** [comment]
I wonder if it's something iPad related. If you can DM me on Discord Aziz#7777 I'll try to take a look at it for you tomorrow after work

**Comment by Joe00** [comment]
Ok I've sent you a friend request

**Comment by Joe00** [comment]
Solved in latest release
